on:
  workflow_call:
    inputs:
      check:
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Bootstrap
      run: |
        sudo apt install python3-setuptools ttfautohint build-essential libffi-dev libgit2-dev -y
        make configure

    - name: Build
      run: |
        make build

    - name: Check
      if: inputs.check
      run: make check

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Lilex
        path: build/
    
    - name: Upload reports
      if: inputs.check
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: reports/
