name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bootstrap
      run: sudo make bootstrap

    - name: Build Lilex
      run: make

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: Lilex
        path: build/
