name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Bootstrap
      run: |
        sudo apt install python3-setuptools ttfautohint build-essential libffi-dev libgit2-dev -y
        make configure

    - name: Build
      run: |
        make bundle
        rm bundle/Lilex.zip

    - name: Upload bundle
      uses: actions/upload-artifact@v3
      with:
        name: Lilex
        path: bundle/
