name: Publish preview

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.0.0

    - name: Bootstrap
      run: |
        sudo apt install python3-setuptools ttfautohint build-essential libffi-dev libgit2-dev -y
        make configure
        make configure_preview

    - name: Build Lilex
      run: make build

    - name: Build preview
      run: make build_preview

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./preview/dist
