name: Quality Assurance

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      check: true
  